name: Pester
on:
  push:
    branches: [main]
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pester tests
        run: |
          Set-PSRepository psgallery -InstallationPolicy 'trusted'
          Install-Module -Name Pester -Confirm:$false -Force
          Install-Module -Name PSScriptAnalyzer -Confirm:$false -Force
          $Path = Get-ChildItem -Path 'IPv4Toolbox' -Recurse -Directory -Filter 'Tests' | Select-Object -First 1 -ExpandProperty 'FullName' | Resolve-Path -Relative
          Write-Host $Path
          Invoke-Pester -Path $Path -Output 'Detailed'
        shell: pwsh
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: test module
        id: test_module
        uses: zyborg/pester-tests-report@v1
        with:
          include_paths: IPv4Toolbox/0.1.0/Tests
          exclude_paths: tests/powershell1,tests/powershell2
          exclude_tags: skip_ci
          report_name: module_tests
          report_title: My Module Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: dump test results
        shell: pwsh
        run: |
          Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
          Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
          Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'
