name: Pester
on:
  push:
    branches:
      - "development"
      - "master"
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pester tests
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted'
          Install-Module -Name 'Pester' -Confirm:$false -Force
          Install-Module -Name 'PSScriptAnalyzer' -Confirm:$false -Force
          $Path = Get-ChildItem -Path 'IPv4Toolbox' -Recurse -Directory -Filter 'Tests' | Select-Object -First 1 -ExpandProperty 'FullName' | Resolve-Path -Relative
          Write-Host $Path
          Invoke-Pester -Path $Path -Output 'Detailed'
        shell: pwsh
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pester tests
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted'
          Install-Module -Name 'Pester' -Confirm:$false -Force
          Install-Module -Name 'PSScriptAnalyzer' -Confirm:$false -Force
          $Path = Get-ChildItem -Path 'IPv4Toolbox' -Recurse -Directory -Filter 'Tests' | Select-Object -First 1 -ExpandProperty 'FullName' | Resolve-Path -Relative
          Write-Host $Path
          Invoke-Pester -Path $Path -Output 'Detailed'
        shell: pwsh
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pester tests
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted'
          Install-Module -Name 'Pester' -Confirm:$false -Force
          Install-Module -Name 'PSScriptAnalyzer' -Confirm:$false -Force
          $Path = Get-ChildItem -Path 'IPv4Toolbox' -Recurse -Directory -Filter 'Tests' | Select-Object -First 1 -ExpandProperty 'FullName' | Resolve-Path -Relative
          Write-Host $Path
          Invoke-Pester -Path $Path -Output 'Detailed'
        shell: pwsh
